# Generated by Django 3.0.6 on 2020-05-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gideon', '0003_post_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
