# Generated by Django 3.0.6 on 2020-05-13 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annunziata', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
