# Generated by Django 3.0.6 on 2020-05-13 14:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annunziata', '0003_postc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Postc',
            new_name='Post',
        ),
    ]
