# Generated by Django 3.0.6 on 2020-05-13 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annunziata', '0005_remove_post_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
